# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  SubscriptionID: '23a859c1-062c-45bf-a863-2a4341b55444'  # ton ID

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1(23a859c1-062c-45bf-a863-2a4341b55444)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Host "Listing resources in subscription $(SubscriptionID)..."
        $resources = az resource list --subscription $(SubscriptionID) --query "[].id" -o tsv
        foreach ($resource in $resources) {
          Write-Host "Deleting $resource"
          az resource delete --ids $resource
        }
    displayName: 'Delete all Azure resources'
